// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA36rRHpdGQ33H5fZMnkq6xd-M7aJZ9sQ',
    appId: '1:973886845768:web:78ca885616fe1aa90ff97d',
    messagingSenderId: '973886845768',
    projectId: 'taxcompdb',
    authDomain: 'taxcompdb.firebaseapp.com',
    databaseURL: 'https://taxcompdb-default-rtdb.firebaseio.com',
    storageBucket: 'taxcompdb.appspot.com',
    measurementId: 'G-9HEZV9CG6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SsNp4ESI_u93djkVfIEyM5FC8UPHLx8',
    appId: '1:973886845768:android:d91abab020b72ebf0ff97d',
    messagingSenderId: '973886845768',
    projectId: 'taxcompdb',
    databaseURL: 'https://taxcompdb-default-rtdb.firebaseio.com',
    storageBucket: 'taxcompdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VDwAmwKwgVEiGaC11qhxgbI7FIRDEs4',
    appId: '1:973886845768:ios:078eb9887459535b0ff97d',
    messagingSenderId: '973886845768',
    projectId: 'taxcompdb',
    databaseURL: 'https://taxcompdb-default-rtdb.firebaseio.com',
    storageBucket: 'taxcompdb.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2VDwAmwKwgVEiGaC11qhxgbI7FIRDEs4',
    appId: '1:973886845768:ios:078eb9887459535b0ff97d',
    messagingSenderId: '973886845768',
    projectId: 'taxcompdb',
    databaseURL: 'https://taxcompdb-default-rtdb.firebaseio.com',
    storageBucket: 'taxcompdb.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );
}
